server:
  port: 48081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.105.7:3306/street_taco?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: street_taco
    password: cHTiLFLPesfmy8Y3

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  miniapp:
    appid: wx0285acfa4cccda04
    secret: e82e523ac33d1c9e3d1fb95b339887eb

jwt:
  secret: street_taco_test_secret_key
